# Generated by Django 2.2.2 on 2019-07-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlackUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("slack_id", models.CharField(max_length=20, unique=True)),
                ("firstname", models.CharField(default="", max_length=50)),
                ("lastname", models.CharField(default="", max_length=50)),
                ("email", models.CharField(blank=True, max_length=100)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("chef", "chef"),
                            ("cleaner", "cleaner"),
                            ("guest", "guest"),
                            ("security", "security"),
                            ("staff", "staff"),
                        ],
                        default="staff",
                        max_length=30,
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        default="https://placehold.it/128x128", max_length=512
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="MealSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast", models.BooleanField(default=False)),
                ("lunch", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_v2.SlackUser",
                    ),
                ),
            ],
        ),
    ]
