# Generated by Django 2.2.2 on 2019-07-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app_v2", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="slackuser", name="last_login"),
        migrations.RemoveField(model_name="slackuser", name="password"),
    ]
