# Generated by Django 2.2.2 on 2019-07-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app_v2", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="mealsession", old_name="breakfast", new_name="status"
        ),
        migrations.RemoveField(model_name="mealsession", name="lunch"),
        migrations.RemoveField(model_name="mealsession", name="user"),
        migrations.CreateModel(
            name="MealService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast", models.BooleanField(default=False)),
                ("lunch", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_v2.SlackUser",
                    ),
                ),
            ],
        ),
    ]
