# Generated by Django 2.2.2 on 2019-07-27 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("app_v2", "0003_auto_20190727_0222")]

    operations = [
        migrations.AddField(
            model_name="slackuser",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slackuser",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name="MealSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast", models.BooleanField(default=False)),
                ("lunch", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_v2.SlackUser",
                    ),
                ),
            ],
        ),
    ]
