#!/bin/bash

export DATABASE_URL="$OPENSHIFT_POSTGRESQL_DB_URL"
python "$OPENSHIFT_REPO_DIR"waitress/manage.py collectstatic --noinput
python "$OPENSHIFT_REPO_DIR"waitress/manage.py makemigrations
python "$OPENSHIFT_REPO_DIR"waitress/manage.py migrate
