# Generated by Django 2.2.2 on 2019-06-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
