# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0002_remove_passphrase_user")]

    operations = [
        migrations.AlterField(
            model_name="slackuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    (b"chef", b"chef"),
                    (b"cleaner", b"cleaner"),
                    (b"guest", b"guest"),
                    (b"security", b"security"),
                    (b"staff", b"staff"),
                ],
                default=b"staff",
                max_length=20,
            ),
        )
    ]
