# Generated by Django 2.2.5 on 2020-01-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pantryservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PantryService',
            new_name='Pantry',
        ),
    ]
