# Generated by Django 2.2.9 on 2020-03-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0009_auto_20200111_0054")]

    operations = [migrations.DeleteModel(name="Pantry")]
